### ISSUE TITLE
新手一个 Cannot GET /

### ISSUE THREAD

**Issue by reyboo** [zhaotoday/element-plus#1]
安装完好了，npm run dev 后 首页提示Cannot GET /
是不是因为根目录没有index.html的原因？

**Comment by zhaotoday** [comment]
@reyboo 
看看 node_modules 目录下有没有 node-sass 文件夹，如果没有请重新安装 node-sass（命令：npm install node）。
node-sass 的安装经常出问题，我也碰到类似的情况。

**Comment by reyboo** [comment]
@zhaotoday 
node_modules 目录下有node-sass和sass-loader文件夹，里面也有源文件。
但我还是重新执行了一遍cnpm install --save-dev node-sass sass-loader
启动成功，问题解决。
谢谢！

**Comment by zhaotoday** [comment]
@reyboo 
不客气。
