### ISSUE TITLE
这两天刚学vue，纯新手一枚

### ISSUE THREAD

**Issue by fantaohaofan** [zhaotoday/element-plus#11]
安装的时候apples貌似安装失败，找不到对应的版本，然后自作主张将package.json的 "apples": "0.0.3" 改成了"apples": "*" 。
之后的之后，
就像前面有个issue说的那样了
## Cannot GET /  

但是比较确定的是node-sass应该是成功安装了的。看到了能帮忙解答一二么，多谢了

**Comment by zhaotoday** [comment]
@fantaohaofan 
问题已经修复。
