### ISSUE TITLE
项目dome地址进不去啊

### ISSUE THREAD

**Issue by ynsui** [zhaotoday/element-plus#12]

**Comment by zhaotoday** [comment]
@wobuchizhunao 
换服务器了，暂时还没重新部署，过几天会布上去。
服务端代码我也提交到 GitHub 了，您可以自己在本地跑起来：
https://github.com/zhaotoday/koa-mvc-framework 。

**Comment by zhaotoday** [comment]
@wobuchizhunao 
可以访问了：
http://admin.liruan.cn/#/articles
用户：admin
密码：123456
