### ISSUE TITLE
XHR failed loading: OPTIONS "http://localhost:3002/apis/v1/actions/login"

### ISSUE THREAD

**Issue by hexian** [zhaotoday/element-plus#15]
Chrome控制台报错： 
 OPTIONS http://localhost:3002/apis/v1/actions/login net::ERR_CONNECTION_REFUSED
XHR failed loading: OPTIONS "http://localhost:3002/apis/v1/actions/login".
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined

是不是后台服务端没有启动？

**Comment by zhaotoday** [comment]
@hexian 
是的。
换服务器了，暂时还没重新部署。
服务端代码我也提交到 GitHub 了，您可以自己在本地跑起来：
https://github.com/zhaotoday/koa-mvc-framework 。

**Comment by zhaotoday** [comment]
@hexian 
可以访问了：
http://admin.liruan.cn/#/articles
用户：admin
密码：123456
