### ISSUE TITLE
请教下demo 中的i18next 调用方式

### ISSUE THREAD

**Issue by shaode** [zhaotoday/element-plus#4]
看到引入了i18next ,想问下页面上怎么调用

**Comment by zhaotoday** [comment]
@shaode 国际化我后面会专门整理下，不过最近没时间。可以先关注：https://github.com/zhaotoday/i18n 。

**Comment by shaode** [comment]
@zhaotoday 我看到这个在整理，不知道现在的demo里面在页面中怎么调用，调用的部分有些吗？ 是和vue-i18n 一样用 $t('a.xxx.xxx')，还是有自己的写法，我用$t没成功，想问下

**Comment by Andervip** [comment]
烦请在添加一些模块 的开发  方便学习，谢谢！

**Comment by zhaotoday** [comment]
@shaode @Andervip 实在抱歉，最近公司在赶项目，没时间整理。后续会花些时间理下，优化下样式，多放几个模块出来。

**Comment by xyzzlaozheng** [comment]
@zhaotoday ,你好,想请教权限管理怎么配置

**Comment by zhaotoday** [comment]
由于公司项目做国际化的场景几乎没有了，所以暂时把 i18n 去掉了，可以先自己研究下。
