### ISSUE TITLE
运行控制台出现很多警告

### ISSUE THREAD

**Issue by sumingfeng** [zhaotoday/element-plus#5]
![image](https://user-images.githubusercontent.com/4383224/27670135-892f1d04-5cbd-11e7-9383-b6ed2e8ad16c.png)
自己已解决，谢谢！

**Comment by lilywang711** [comment]
怎么解决的

**Comment by sumingfeng** [comment]
这个项目问题比较多：
1.页面布局没采用iview官方推荐的响应式布局，而是固定布局。
这是我按照官方改的：
![image](https://user-images.githubusercontent.com/4383224/28651297-b4262726-72b3-11e7-891e-38ec42d91642.png)
2.组件名采用了和html5标签相同的名字，如header、body，所以会弹出很多警告。上图我已经区分开了。
3.文件层次结构分得太细，比如组件没必要将css分开，没必要一个一个组件都外链，重复引用相同的模块，影响可阅读性，导致很多index文件、很多文件夹。这种方式有利也有弊端，可以根据自己的需求进行简化。

**Comment by zhaotoday** [comment]
@sumingfeng 
谢谢您的建议！
第 1 点这样做的原因，我是参考京东的管理后台，定宽居中，注意力比较容易集中。不过这个后面会再做一些权衡，响应式确实会更加美观；
第 2 点，这个问题确实存在，不过构建后的代码是不会报错。起初的想法也是想做下优化，不过工作比较忙，感觉优先级不高，后续再处理；
第 3 点，看个人和团队习惯吧，您的建议我会再斟酌下。
