### ISSUE TITLE
dev Cannot read property 'data' of null"

### ISSUE THREAD

**Issue by luxifeng2014** [zhaotoday/element-plus#7]
Error in render function: "TypeError: Cannot read property 'data' of null"

found in

---> <List> at /Users/luluxifeng/work/pro/iview-master/src/app/Articles/List/index.vue
       <Articles> at /Users/luluxifeng/work/pro/iview-master/src/app/Articles/index.vue
         <Body> at /Users/luluxifeng/work/pro/iview-master/src/app/Layout/components/Body/index.vue
           <Layout> at /Users/luluxifeng/work/pro/iview-master/src/app/Layout/index.vue
             <Root> at /Users/luluxifeng/work/pro/iview-master/src/app/Root/index.vue
               <App> at /Users/luluxifeng/work/pro/iview-master/src/App.vue
                 <Root>

**Comment by zhaotoday** [comment]
@luxifeng2014 
BUG 已修复。
