### ISSUE TITLE
node run dev的时候报错说找不到\node_modules\node-sass\vendor

### ISSUE THREAD

**Issue by bubucuo** [zhaotoday/element-plus#8]
请问楼主，node install安装成功，启动调试的时候报错说找不到\node_modules\node-sass\vendor是什么原因，在线等

**Comment by zhaotoday** [comment]
可能是 node 的版本比较低，试试升级 node。

**Comment by bubucuo** [comment]
去\node_modules\node-sass\里npｍ install了一下，生成了vendor，所以这个问题解决，谢谢楼主。但是启动成功之后，在登陆页面报了几个错。无法正常使用，
[Vue warn]: Do not use built-in or reserved HTML elements as component id: I
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Header
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Body
vue.esm.js?65d7:479 [Vue warn]: Property or method "submit" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Login> at F:\1-gitspace\iview\src\app\Login\index.vue
       <Root> at F:\1-gitspace\iview\src\app\Root\index.vue
         <App> at F:\1-gitspace\iview\src\App.vue
           <Root>
。点击事件on-enter也说未定义。vue.esm.js?65d7:479 [Vue warn]: Invalid handler for event "on-enter": got undefined。
截图发不了，如果楼主有时间能帮忙看一下，感激不尽~

**Comment by zhaotoday** [comment]
[Vue warn] 的 3 个提示是组件命名的问题，后续处理，构建后不会提示，其他 BUG 已修复。  
谢谢提醒，前段时间一直忙，没精力整理。  
另外，`node-sass` 安装失败的可以看下我的这篇文章：http://www.qianduan.org/post-474.html
